import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

// Get screen dimensions
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const isSmallDevice = SCREEN_WIDTH < 375;

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f03a6c',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: Platform.OS === 'android' ? 12 : 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  backButton: {
    padding: 5,
  },
  headerTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: '400',
    textAlign: 'center',
    flex: 1,
    fontFamily: 'Roboto',
  },
  searchButton: {
    padding: 5,
  },
  contentContainer: {
    flex: 1,
    paddingBottom: 80, // Space for the floating action button
  },
  monthSelectorContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  monthTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  monthTitleText: {
    fontSize: isSmallDevice ? 18 : 22,
    fontWeight: '500',
    marginRight: 5,
  },
  todayLabel: {
    fontSize: isSmallDevice ? 16 : 18,
    color: '#f03a6c',
    fontWeight: '500',
  },
  calendarContainer: {
    padding: 10,
    backgroundColor: 'white',
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
  },
  calendarNavButton: {
    fontSize: 24,
    color: '#f03a6c',
    paddingHorizontal: 10,
  },
  calendarMonthYear: {
    fontSize: isSmallDevice ? 16 : 18,
    color: '#f03a6c',
    fontWeight: '500',
  },
  daysOfWeekContainer: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  dayOfWeek: {
    flex: 1,
    textAlign: 'center',
    color: '#f03a6c',
    fontWeight: '500',
    fontSize: isSmallDevice ? 12 : 14,
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  calendarDayContainer: {
    flex: 1,
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    minHeight: isSmallDevice ? 30 : 35,
  },
  calendarDayLabel: {
    fontSize: isSmallDevice ? 14 : 16,
  },
  calendarDateLabel: {
    fontSize: isSmallDevice ? 14 : 16,
    color: '#666',
  },
  currentDateLabel: {
    color: '#f03a6c',
    fontWeight: '700',
  },
  selectedDay: {
    backgroundColor: '#ffebf0',
    borderWidth: 1,
    borderColor: '#f03a6c',
  },
  selectedDayText: {
    fontWeight: '700',
    color: '#f03a6c',
  },
  otherMonthDay: {
    opacity: 0.5,
  },
  otherMonthDayText: {
    color: '#aaa',
  },
  currentDateIndicator: {
    height: 3,
    width: 20,
    backgroundColor: '#f03a6c',
    marginTop: 5,
    borderRadius: 1.5,
  },
  taskSectionContainer: {
    paddingTop: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    backgroundColor: 'white',
    marginHorizontal: 10,
    marginVertical: 5,
    borderRadius: 10,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  taskSectionTitle: {
    fontSize: isSmallDevice ? 16 : 18,
    fontWeight: '500',
    paddingHorizontal: 20,
    marginBottom: 15,
    color: '#333',
  },
  taskContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: isSmallDevice ? 12 : 15,
    paddingHorizontal: 20,
  },
  taskTextContainer: {
    flex: 1,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingRight: 5,
  },
  taskTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  taskTimeText: {
    fontSize: 12,
    color: '#888',
    marginLeft: 4,
  },
  taskCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ff9999',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  taskCheckboxInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'white',
  },
  taskCheckboxCompleted: {
    backgroundColor: '#f03a6c',
    borderColor: '#f03a6c',
  },
  taskDescription: {
    flex: 1,
    fontSize: isSmallDevice ? 16 : 18,
    color: '#333',
    flexWrap: 'wrap',
  },
  taskOptionsButton: {
    padding: 8,
    borderRadius: 15,
  },
  taskOptionsIcon: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#666',
  },
  separator: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginHorizontal: 20,
  },
  addTaskButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#f03a6c',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    zIndex: 999,
  },
  addTaskButtonText: {
    fontSize: 30,
    color: 'white',
    lineHeight: Platform.OS === 'ios' ? 58 : 60,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    maxHeight: SCREEN_HEIGHT * 0.8,
  },
  modalTitle: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: '600',
    color: '#333',
    marginBottom: 20,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    fontSize: isSmallDevice ? 14 : 16,
  },
  datePickerButton: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
  },
  datePickerText: {
    fontSize: isSmallDevice ? 14 : 16,
    color: '#333',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    flex: 1,
    padding: isSmallDevice ? 8 : 10,
    borderRadius: 5,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#9CA3AF',
  },
  submitButton: {
    backgroundColor: '#f03a6c',
  },
  modalButtonText: {
    color: 'white',
    fontSize: isSmallDevice ? 14 : 16,
    fontWeight: '500',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTabButton: {
    borderBottomColor: '#f03a6c',
  },
  tabButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#666',
  },
  activeTabButtonText: {
    color: '#f03a6c',
    fontWeight: '600',
  },
  selectedDateContainer: {
    backgroundColor: '#f03a6c',
    padding: 15,
    alignItems: 'center',
  },
  selectedYear: {
    color: 'white',
    fontSize: isSmallDevice ? 14 : 16,
  },
  selectedDayMonth: {
    color: 'white',
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: '500',
  },
  contextMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  contextMenuContainer: {
    position: 'absolute',
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 5,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    minWidth: 120,
  },
  contextMenuItem: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  contextMenuItemText: {
    fontSize: isSmallDevice ? 14 : 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  dateTimeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: isSmallDevice ? 8 : 10,
    paddingRight: isSmallDevice ? 5 : 8,
    borderRadius: 8,
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: '#f03a6c',
    minHeight: 50,
  },
  dateTimeText: {
    marginLeft: 8,
    fontSize: isSmallDevice ? 12 : 14,
    color: '#f03a6c',
    fontWeight: '500',
    flex: 1,
    flexWrap: 'wrap',
    textAlign: 'center',
  },
  taskInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    padding: 12,
    fontSize: isSmallDevice ? 14 : 16,
    marginBottom: 20,
  },
  searchContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  searchModeContainer: {
    flexDirection: 'row',
    marginBottom: 15,
  },
  searchModeButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 15,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeSearchMode: {
    borderBottomColor: '#f03a6c',
  },
  searchModeText: {
    fontSize: isSmallDevice ? 12 : 14,
    color: '#666',
  },
  activeSearchModeText: {
    color: '#f03a6c',
    fontWeight: '500',
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: isSmallDevice ? 14 : 16,
    color: '#333',
  },
  dateSearchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    padding: 12,
    paddingRight: 8,
    minHeight: 50,
  },
  dateSearchText: {
    marginLeft: 8,
    fontSize: isSmallDevice ? 12 : 14,
    color: '#333',
    flex: 1,
    flexWrap: 'wrap',
  },
  closeSearchButton: {
    alignSelf: 'flex-end',
    marginTop: 10,
    padding: 5,
  },
  closeSearchText: {
    color: '#f03a6c',
    fontSize: isSmallDevice ? 12 : 14,
    fontWeight: '500',
  },
  emptyListText: {
    textAlign: 'center',
    fontSize: isSmallDevice ? 14 : 16,
    color: '#666',
    marginTop: 20,
    paddingVertical: 20,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerButton: {
    padding: 5,
    marginLeft: 10,
  },
  taskCheckboxSelected: {
    backgroundColor: '#f03a6c',
    borderColor: '#f03a6c',
  },
  taskStatusIndicator: {
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  completedTaskText: {
    textDecorationLine: 'line-through',
    color: '#888888',
  },
  taskSectionHeader: {
    backgroundColor: '#f8f8f8',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    marginTop: 10,
  },
  taskSectionHeaderText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#444',
  },
  completedTaskSection: {
    opacity: 0.8,
    backgroundColor: '#f9f9f9',
  },
  taskDateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 2,
  },
  taskDateText: {
    fontSize: 12,
    color: '#888',
    marginLeft: 4,
    flexShrink: 1,
    flexWrap: 'wrap',
    width: '90%',
  },
  // Loading styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    minHeight: 200,
  },
  loadingText: {
    fontSize: 16,
    color: '#666',
    marginTop: 10,
  },
});